# Generated by Django 5.0.7 on 2024-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrafos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrafo',
            name='titulo',
            field=models.CharField(default='Título Predeterminado', max_length=200),
        ),
    ]
