# Generated by Django 5.0.7 on 2024-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrafos', '0002_parrafo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrafo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
