name: Django Security Check

on: pull_request_target

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FAIL_LEVEL: WARNING
  ENV_TYPE: pipenv
  PIPENV_IGNORE_VIRTUALENVS: 1  # Forzar la creación de un nuevo entorno virtual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Reemplaza '3.10' con la versión de Python que necesitas

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev  # Instalar dependencias incluyendo las de desarrollo

      - name: Verify Pipfile
        run: |
          cat Pipfile  # Verificar que Django esté listado como una dependencia

      - name: Verify Django installation
        run: |
          PIPENV_IGNORE_VIRTUALENVS=1 pipenv run python -m django --version  # Verifica que Django esté instalado correctamente

      - name: Scan Django settings for security issues
        id: check
        run: |
          PIPENV_IGNORE_VIRTUALENVS=1 pipenv run python manage.py check --deploy  # Usar pipenv para ejecutar el comando de verificación

      - id: results
        run: |
          OUTPUT=$(PIPENV_IGNORE_VIRTUALENVS=1 pipenv run python manage.py check --deploy)  # Ejecuta el comando de verificación de nuevo y captura la salida
          FORMATTED=${OUTPUT//$'\n'/%0A}
          echo ::set-output name=file::**Django Security Check identified issues:** %0A$FORMATTED

      - name: Comment with output
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.results.outputs.file }}`
            })