name: Django Security Check

on: pull_request_target

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FAIL_LEVEL: WARNING

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Reemplaza '3.10' con la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalar dependencias desde requirements.txt
          pip install django  # Instalar Django explícitamente

      - name: Verify Django installation
        run: |
          python -m django --version  # Verifica que Django esté instalado correctamente

      - name: Scan Django settings for security issues
        run: |
          python manage.py check --deploy  # Usar pip para ejecutar el comando de verificación

      - id: results
        run: |
          OUTPUT=$(python manage.py check --deploy)  # Ejecuta el comando de verificación de nuevo y captura la salida
          FORMATTED=${OUTPUT//$'\n'/%0A}
          echo ::set-output name=file::**Django Security Check identified issues:** %0A$FORMATTED

      - name: Comment with output
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.results.outputs.file }}`
            })